version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: CI/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: CI/start_container.sh
      timeout: 300
      runas: root
